export const NIGERIAN_UNIVERSITIES = [
  'University of Ibadan',
  'University of Nigeria, Nsukka',
  'Obafemi Awolowo University',
  'Ahmadu Bello University',
  'University of Lagos',
  'University of Benin',
  'Bayero University, Kano',
  'University of Calabar',
  'University of Ilorin',
  'University of Jos',
  'University of Maiduguri',
  'Usmanu Danfodiyo University',
  'University of Port Harcourt',
  'Federal University of Technology, Owerri',
  'Federal University of Technology, Akure',
  'Modibbo Adama University, Yola',
  'Federal University of Technology, Minna',
  'Nigerian Defence Academy',
  'University of Abuja',
  'Abukakar Tafawa Balewa University',
  'Federal University of Agriculture, Abeokuta',
  'University of Agriculture, Makurdi',
  'Michael Okpara University of Agriculture',
  'Nnamdi Azikiwe University',
  'University of Uyo',
  'National Open University of Nigeria',
  'Federal University of Petroleum Resources, Effurun',
  'Federal University, Lokoja',
  'Federal University, Lafia',
  'Federal University, Kashere',
  'Federal University, Wukari',
  'Federal University, Dutsin-Ma',
  'Federal University, Dutse',
  'Federal University, Birnin Kebbi',
  'Federal University, Gusau',
  'Federal University, Gashua',
  'Federal University, Oye-Ekiti',
  'Federal University, Ndifu-Alike',
  'Federal University, Otuoke',
  'Federal University of Health Sciences',
  'Abia State University',
  'Adamawa State University',
  'Adekunle Ajasin University',
  'Akwa Ibom State University',
  'Ambrose Alli University',
  'Chukwuemeka Odumegwu Ojukwu University',
  'Bauchi State University',
  'Benue State University',
  'Delta State University',
  'Ebonyi State University',
  'Edo State University (Iyamho)',
  'Ekiti State University',
  'Enugu State University of Science and Technology',
  'Gombe State University',
  'Ibrahim Badamasi Babangida University',
  'Ignatius Ajuru University of Education',
  'Imo State University',
  'Kaduna State University',
  'Kano University of Science & Technology',
  'Kebbi State University of Science and Technology',
  'Kogi State University',
  'Kwara State University',
  'Lagos State University',
  'Ladoke Akintola University of Technology',
  'Nasarawa State University',
  'Niger Delta University',
  'Olabisi Onabanjo University',
  'Ondo State University of Science and Technology',
  'Osun State University',
  'Plateau State University',
  'Rivers State University',
  'Sokoto State University',
  'Taraba State University',
  'Umaru Musa Yar\'Adua University',
  'Yobe State University',
  'Zamfara State University',
  'Tai Solarin University of Education',
  'Confluence University of Science and Technology',
  'University of Delta',
  'Dennis Osadebay University'
]
