export const NIGERIAN_UNIVERSITIES = [
  "Abia State University",
  "Abiola Ajimobi Technical University (formerly First Technical University)",
  "Abubakar Tafawa Balewa University",
  "Abukakar Tafawa Balewa University",
  "Achievers University",
  "Adamawa State University",
  "Adekunle Ajasin University",
  "Adeleke University",
  "Admiralty University Nigeria",
  "African Thinkers Community of Inquiry College of Education (University arm if licensed)",
  "African University of Science and Technology",
  "Ahmadu Bello University",
  "Ahman Pategi University",
  "Air Force Institute of Technology",
  "Ajayi Crowther University",
  "Akwa Ibom State University",
  "Al-Ansar University",
  "Al-Hikmah University",
  "Al-Istiqama University",
  "Al-Muhibbah Open University",
  "Aliko Dangote University of Science and Technology",
  "Amadeus University",
  "Ambrose Alli University",
  "American University of Nigeria",
  "Anan University",
  "Anchor University",
  "Arthur Jarvis University",
  "Atiba University",
  "Augustine University",
  "Ave Maria University",
  "Ave Maria University Piyanko",
  "Babcock University",
  "Bamidele Olumilua University of Education, Science and Technology",
  "Baze University",
  "Bayero University",
  "Bayero University, Kano",
  "Bayelsa Medical University",
  "Bauchi State University",
  "Bells University of Technology",
  "Benson Idahosa University",
  "Benue State University",
  "Bingham University",
  "Borno State University",
  "Bowen University",
  "British Canadian University",
  "British University of Nigeria",
  "Caleb University",
  "Capital City University",
  "Caritas University",
  "Chrisland University",
  "Christopher University",
  "Chukwuemeka Odumegwu Ojukwu University",
  "Claretian University of Nigeria",
  "Clifford University",
  "Coal City University",
  "College of Nursing,Bowen University Teaching Hospital,Ogbomoso,Oyo state",
  "Confluence University of Science and Technology",
  "Cosmos University",
  "Covenant University",
  "Covenant University of Medical Sciences (where applicable if licensed)",
  "Crescent University",
  "Crown-Hill University",
  "Delta State University",
  "Dennis Osadebay University",
  "Dominican University",
  "Dominion University",
  "Ebonyi State University",
  "Edo State University",
  "Edo State University (Iyamho)",
  "Edwin Clark University",
  "Edusoko University",
  "Eko University of Medical and Health Sciences",
  "Ekiti State University",
  "El-Amin University",
  "Elizade University",
  "Enugu State University of Science and Technology",
  "Evangel University",
  "Federal University Birnin Kebbi",
  "Federal University Dutse",
  "Federal University Dutsin-Ma",
  "Federal University Gashua",
  "Federal University Gusau",
  "Federal University Kashere",
  "Federal University Lafia",
  "Federal University Lokoja",
  "Federal University Otuoke",
  "Federal University Oye-Ekiti",
  "Federal University Wukari",
  "Federal University of Agriculture, Abeokuta",
  "Federal University of Agriculture, Makurdi",
  "Federal University of Agriculture, Zuru",
  "Federal University of Allied Health Sciences, Enugu",
  "Federal University of Applied Sciences, Kachia",
  "Federal University, Birnin Kebbi",
  "Federal University, Dutse",
  "Federal University, Dutsin-Ma",
  "Federal University, Gashua",
  "Federal University, Gusau",
  "Federal University, Kashere",
  "Federal University, Lafia",
  "Federal University, Lokoja",
  "Federal University, Ndifu-Alike",
  "Federal University, Otuoke",
  "Federal University, Oye-Ekiti",
  "Federal University, Wukari",
  "Federal University of Health Sciences",
  "Federal University of Health Sciences, Azare",
  "Federal University of Health Sciences, Ila-Orangun",
  "Federal University of Health Sciences, Otukpo",
  "Federal University of Petroleum Resources, Effurun",
  "Federal University of Technology, Akure",
  "Federal University of Technology, Babura",
  "Federal University of Technology, Ikot Abasi",
  "Federal University of Technology, Minna",
  "Federal University of Technology, Owerri",
  "Federal University of Environment and Technology, Koroma/Saakpenwa (if operational under current approvals)",
  "Fountain University",
  "Gerar University of Medical Sciences",
  "Glorious Vision University",
  "Godfrey Okoye University",
  "Gombe State University",
  "Gombe State University of Science and Technology",
  "Greenfield College University",
  "Greenfield University",
  "Hallmark University",
  "Havilla University",
  "Hensard University",
  "Hezekiah University",
  "Hillside University of Science and Technology",
  "Ibrahim Badamasi Babangida University",
  "Iconic Open University",
  "Igbinedion University",
  "Ignatius Ajuru University of Education",
  "Imo State University",
  "Isaac Balami University of Aeronautics and Management",
  "James Hope University",
  "Joseph Ayo Babalola University",
  "Kaduna State University",
  "Kano University of Science & Technology",
  "Karl Kumm University",
  "Kebbi State University of Science and Technology",
  "Kings University",
  "Kingsley Ozumba Mbadiwe University",
  "Kogi State University",
  "Kwara State University",
  "Kwara State University of Education",
  "Kwararafa University",
  "Ladoke Akintola University of Technology",
  "Lagos State University",
  "Lagos State University of Education",
  "Lagos State University of Science and Technology",
  "Landmark University",
  "Lead City University",
  "Legacy University",
  "Lighthouse University",
  "Lux Mundi University",
  "Madonna University",
  "Maranatha University",
  "Maranatha University Lagos",
  "Margaret Lawrence University",
  "Maryam Abacha American University of Nigeria",
  "McPherson University",
  "Mercy Medical University",
  "Mewar International University",
  "Michael Okpara University of Agriculture",
  "Michael Okpara University of Agriculture, Umudike",
  "Minaret University",
  "Miva Open University",
  "Modibbo Adama University",
  "Modibbo Adama University, Yola",
  "Mountain Top University",
  "Mudiame University",
  "Nasarawa State University",
  "National Open University of Nigeria",
  "Newgate University Minna",
  "Niger Delta University",
  "Nigerian Army University, Biu",
  "Nigerian British University",
  "Nigerian Defence Academy",
  "Nigerian Maritime University",
  "Nigerian Police Academy",
  "Nnamdi Azikiwe University",
  "Nile University of Nigeria",
  "Novena University",
  "Obafemi Awolowo University",
  "Obong University",
  "Olabisi Onabanjo University",
  "Olusegun Agagu University of Science and Technology",
  "Ondo State University of Science and Technology",
  "Osun State University",
  "Oduduwa University",
  "Oduduwa university,Ipetumodu",
  "Pacesetter University",
  "PAMO University of Medical Sciences",
  "Pan-Atlantic University",
  "Paul University",
  "Pen Resource University",
  "Philomath University",
  "Phoenix University Agwada",
  "Plateau State University",
  "Precious Cornerstone University",
  "Prime University Abuja",
  "Prince Abubakar Audu University",
  "Rayhaan University",
  "Redeemer’s University",
  "Renaissance University",
  "Rhema University",
  "Rivers State University",
  "Sa’adu Zungur University",
  "Salem University",
  "Samuel Adegboyega University",
  "Skyline University Nigeria",
  "Sokoto State University",
  "Southern Delta University",
  "Spiritan University",
  "Sule Lamido University",
  "Summit University",
  "Tai Solarin University of Education",
  "Tansian University",
  "Taraba State University",
  "Thomas Adewumi University",
  "Topfaith University",
  "Trinity University",
  "Trinity University Yaba",
  "Umaru Musa Yar’Adua University",
  "University of Abuja",
  "University of Africa",
  "University of Agriculture, Makurdi",
  "University of Benin",
  "University of Calabar",
  "University of Cross River State",
  "University of Delta",
  "University of Ibadan",
  "University of Ilesa",
  "University of Ilorin",
  "University of Jos",
  "University of Lagos",
  "University of Maiduguri",
  "University of Medical Sciences",
  "University of Nigeria, Nsukka",
  "University of Offa",
  "University of Port Harcourt",
  "University of Uyo",
  "University on the Niger",
  "Usmanu Danfodiyo University",
  "Venite University",
  "Veritas University",
  "Wellspring University",
  "Wesley University",
  "Westlands University",
  "West Midlands Open University",
  "Western Delta University",
  "Wigwe University",
  "Yakubu Gowon University (formerly University of Abuja, if and when officially renamed)",
  "Yobe State University",
  "Zamfara State University"
];
